defmodule Pan.Repo.Migrations.RestoreFeedUrlsOverwrittenByRedirects do
  use Ecto.Migration

  # Until the fix in Pan.Parser.Feed.persist_redirect_target/2, every redirect
  # target became the feed URL right away, before anything was fetched from
  # it. Temporary redirects to maintenance pages or homepages (wartung.wdr.de,
  # app.screencast.com, www.podomatic.com/404.html, ...) thereby replaced
  # working feed URLs for good. Restores the previous URL from alternate_feeds
  # where it serves a feed again with the podcast's title (probed 2026-10-02
  # against the prod backup of that night: 368 live previous URLs, 284 with
  # matching titles, 283 of those still failing; 63 of those left out, as
  # their previous URL just redirects to the current one). The broken URL is
  # kept in alternate_feeds; a feed is only changed if it still has that URL.
  # The podcasts are made due now (UTC, the column is naive UTC).
  @restore [
    {63, "https://wir.muessenreden.de/feed/podcast/", "http://wir.muessenreden.de/feed/podcast/"},
    {228, "https://wartung.wdr.de",
     "https://www1.wdr.de/radio/podcasts/wdr5/dokfuenf140.podcast"},
    {230, "https://wartung.wdr.de",
     "https://www1.wdr.de/radio/podcasts/wdr5/dasphilosophischeradio100.podcast"},
    {268,
     "https://www.deutschlandfunkkultur.de/podcast-breitband-medien-und-digitale-kultur-ganze-sendung-100.xml",
     "https://www.deutschlandfunkkultur.de/podcast-breitband-medien-und-digitale-kultur-ganze-sendung.1552.de.podcast.xml"},
    {274,
     "https://choice.npr.org/index.html?origin=https://www.npr.org/rss/podcast.php?id=510307",
     "https://feeds.npr.org/510307/podcast.xml"},
    {310, "http://feeds.thebuglepodcast.com/thebuglefeed",
     "http://feeds.feedburner.com/thebuglefeed"},
    {370, "https://bartocast.de/?feed=podcast&podcast_series=bartocast/",
     "http://bartocast.de/?feed=podcast"},
    {398, "https://fernostwaerts.de/feed/opus/", "https://fernostwaerts.de/feed/m4a/"},
    {423, "http://wartung.wdr.de/",
     "https://www1.wdr.de/mediathek/audio/zeitzeichen/zeitzeichen-podcast-100.podcast"},
    {478, "http://podcast.hr2.de/derTag/podcast.xml", "https://podcast.hr.de/derTag/podcast.xml"},
    {577,
     "https://choice.npr.org/index.html?origin=https://www.npr.org/rss/podcast.php?id=510298",
     "https://feeds.npr.org/510298/podcast.xml"},
    {583, "https://changelog.com/founderstalk", "https://changelog.com/founderstalk/feed"},
    {590,
     "https://choice.npr.org/index.html?origin=https://www.npr.org/rss/podcast.php?id=381444908",
     "https://feeds.npr.org/381444908/podcast.xml"},
    {602,
     "https://choice.npr.org/index.html?origin=https://www.npr.org/rss/podcast.php?id=510282",
     "https://feeds.npr.org/510282/podcast.xml"},
    {604, "https://feeds.slack-podcast.com/workinprogress", "http://usave.it/t/Ek30s1L2"},
    {608, "https://changelog.com/rfc", "https://changelog.com/rfc/feed"},
    {731, "https://wartung.wdr.de",
     "https://www1.wdr.de/mediathek/audio/wdr5/wdr5-presseclub/presseclub304.podcast"},
    {780, "https://relay.fm/membersonly/feed",
     "http://feeds.soundcloud.com/users/soundcloud:users:268394884/sounds.rss"},
    {849,
     "https://choice.npr.org/index.html?origin=https://www.npr.org/rss/podcast.php?id=510289",
     "https://feeds.npr.org/510289/podcast.xml"},
    {1068, "https://feeds.podcastmirror.com/slowgerman", "https://slowgerman.com/feed/podcast"},
    {1103, "http://campusradiodresden.de/feed/mp3/",
     "http://feeds.feedburner.com/CampusradioDresden"},
    {1303, "http://www.wheresthegringo.com/cgi-sys/suspendedpage.cgi",
     "http://www.wheresthegringo.com/feed/podcast/"},
    {1468, "http://www.spanishpodcast.org/cgi-sys/suspendedpage.cgi",
     "http://www.spanishpodcast.org/archivos/Spanishpodcast.xml"},
    {1630, "https://www.potencialmillonario.com/cgi-sys/suspendedpage.cgi",
     "https://www.potencialmillonario.com/feed/"},
    {1949, "https://www.vietnamesepod101.com/wp-feed-audio-video.php",
     "https://www.vietnamesepod101.com/wp/wp-feed-audio-video.php"},
    {1951, "https://www.turkishclass101.com/wp-feed-audio-video.php",
     "https://www.turkishclass101.com/wp/wp-feed-audio-video.php"},
    {1954, "https://www.thaipod101.com/wp-feed-audio-video.php",
     "https://www.thaipod101.com/wp/wp-feed-audio-video.php"},
    {1957, "https://www.swedishpod101.com/wp-feed-audio-video.php",
     "https://www.swedishpod101.com/wp/wp-feed-audio-video.php"},
    {1997, "https://www.russianpod101.com/search/feed+php",
     "https://www.russianpod101.com/wp-feed-audio-video.php"},
    {2003, "https://www.portuguesepod101.com/wp-feed-audio-video.php",
     "https://www.portuguesepod101.com/wp/wp-feed-audio-video.php"},
    {2007, "https://www.polishpod101.com/wp-feed-audio-video.php",
     "https://www.polishpod101.com/wp/wp-feed-audio-video.php"},
    {2013, "https://www.persianpod101.com/wp-feed-audio-video.php",
     "https://www.persianpod101.com/wp/wp-feed-audio-video.php"},
    {2017, "https://www.koreanclass101.com/wp-feed-audio-video.php",
     "https://www.koreanclass101.com/wp/wp-feed-audio-video.php"},
    {2020, "https://www.japanesepod101.com/wp-feed-audio.php",
     "https://www.japanesepod101.com/wp/wp-feed-audio.php"},
    {2023, "https://www.italianpod101.com/wp-feed-audio-video.php",
     "https://www.italianpod101.com/wp/wp-feed-audio-video.php"},
    {2033, "https://www.indonesianpod101.com/wp-feed-audio-video.php",
     "https://www.indonesianpod101.com/wp/wp-feed-audio-video.php"},
    {2034, "https://www.hungarianpod101.com/wp-feed-audio-video.php",
     "https://www.hungarianpod101.com/wp/wp-feed-audio-video.php"},
    {2035, "https://www.hindipod101.com/wp-feed-audio-video.php",
     "https://www.hindipod101.com/wp/wp-feed-audio-video.php"},
    {2038, "https://www.hebrewpod101.com/wp-feed-audio-video.php",
     "https://www.hebrewpod101.com/wp/wp-feed-audio-video.php"},
    {2040, "https://www.greekpod101.com/wp-feed-audio-video.php",
     "https://www.greekpod101.com/wp/wp-feed-audio-video.php"},
    {2045, "https://www.francaisavecpierre.com/podcast-au-japon-niv-b2/",
     "https://www.francaisavecpierre.com/feed/podcast/"},
    {2049, "https://www.finnishpod101.com/wp-feed-audio-video.php",
     "https://www.finnishpod101.com/wp/wp-feed-audio-video.php"},
    {2062, "https://www.danishclass101.com/wp-feed-audio-video.php",
     "https://www.danishclass101.com/wp/wp-feed-audio-video.php"},
    {2065, "https://www.czechclass101.com/maintenance.html",
     "http://www.czechclass101.com/wp/wp-feed-audio-video.php"},
    {2073, "https://www.cantoneseclass101.com/wp-feed-audio-video.php",
     "https://www.cantoneseclass101.com/wp/wp-feed-audio-video.php"},
    {2075, "https://www.bulgarianpod101.com/wp-feed-audio-video.php",
     "https://www.bulgarianpod101.com/wp/wp-feed-audio-video.php"},
    {2398, "https://www.lingq.com/blog/category/english-lingq-podcast/",
     "https://englishlingq.com/feed"},
    {2862, "https://www.ebs.co.kr:443/actions/EncodingMngList",
     "http://www.ebs.co.kr/actions/EncodingMngList?cmd=podcastEpisodeList&program_id=10018093"},
    {3421, "https://presentmomentmindfulness.com/rss.xml",
     "http://presentmomentmindfulness.com/rss.xml"},
    {3623, "https://government-shutdown.noaa.gov",
     "https://oceanservice.noaa.gov/rss/noaa-ocean-podcast.xml"},
    {4445, "http://www.scienceoffice.org/cgi-sys/suspendedpage.cgi",
     "http://www.scienceoffice.org/ciencia_por_miudos/podcast.xml"},
    {5102, "http://www.wltr.drupal.publicbroadcasting.net/podcasts/363/rss.xml",
     "http://wltr.drupal.publicbroadcasting.net/podcasts/363/rss.xml"},
    {5252, "http://www.wrvo.drupal.publicbroadcasting.net/podcasts/4773/rss.xml",
     "http://wrvo.drupal.publicbroadcasting.net/podcasts/4773/rss.xml"},
    {5621, "http://www.spacerockethistory.com?feed=podcast",
     "https://spacerockethistory.com/?feed=podcast"},
    {5628, "http://www.wltr.drupal.publicbroadcasting.net/podcasts/814/rss.xml",
     "http://wltr.drupal.publicbroadcasting.net/podcasts/814/rss.xml"},
    {5929, "http://az1-sr3.supercp.com/suspended.page/",
     "https://www.goldenspiralmedia.com/category/timeless/feed"},
    {5995, "http://www.radiowest.kuer.org/podcasts/220/rss.xml",
     "http://radiowest.kuer.org/podcasts/220/rss.xml"},
    {6115, "http://www.polskiedetroit.com/cgi-sys/suspendedpage.cgi",
     "http://www.polskiedetroit.com/polskiedetroit.xml"},
    {6257, "http://feeds.feedburner.com/PipocaLetrada",
     "http://feeds.soundcloud.com/users/soundcloud:users:242029365/sounds.rss?before=293161952"},
    {6372, "http://history.trhonline.com/cgi-sys/suspendedpage.cgi",
     "http://history.trhonline.com/historyrss.pl"},
    {7659, "https://ganglandwire.com/podcast-2/", "https://ganglandwire.com/feed/podcast/"},
    {8043, "https://www.douknowwhoiam.com/cgi-sys/suspendedpage.cgi?feed=podcast",
     "https://www.douknowwhoiam.com/?feed=podcast"},
    {8433, "https://bytesizedbiographies.com/", "https://bytesizedbiographies.com/?feed=podcast"},
    {8559, "http://feeds.feedburner.com/BehindTheMicCFUV",
     "http://feeds.soundcloud.com/users/soundcloud:users:149259094/sounds.rss"},
    {8704, "http://ancienthistory.aadl.org/", "http://www.aadl.org/annarborstories/feed"},
    {8851, "http://5minutebiographies.com/cgi-sys/suspendedpage.cgi",
     "http://5minutebiographies.com/feed/"},
    {8876,
     "https://www.thecreativepenn.com/2010/05/14/podcast-advanced-blogging-tips-for-authors-with-blogging-teacher-paul-cunningham/",
     "https://www.thecreativepenn.com/feed/podcast/"},
    {8895, "http://mysteriouschicago.com/cgi-sys/suspendedpage.cgi",
     "http://mysteriouschicago.com/MysteriousChicagoPodcast.xml"},
    {10371, "https://doheny.org/podcast/", "http://doheny.org/feed/podcast/"},
    {10547, "http://www.clinicalauditsupport.com/cgi-sys/suspendedpage.cgi",
     "http://www.clinicalauditsupport.com/podcast/podcast.xml"},
    {10676, "http://maintenance.webi.it.ubc.ca",
     "https://therapeuticseducation.org/feed/podcast"},
    {11046,
     "https://thetestingpsychologist.com/podcast-crossover-with-school-psyched-rebecca-comizio-rachael-donnelly-and-eric-elias/",
     "https://thetestingpsychologist.com/feed/podcast/"},
    {11077, "http://p3nlhclust404.shr.prod.phx3.secureserver.net/SharedContent/redirect_0.html",
     "https://stanfordhispanicbroadcasting.org/feed/podcast/"},
    {11182, "https://radiolacan.com/es/topic/704/3?rss=1",
     "http://www.radiolacan.com/es/topic/704/3?rss=1"},
    {11520, "https://jungnapratica.com.br/podcast_011_jornada_de_autoconhecimento/",
     "https://www.jungnapratica.com.br/feed/podcast/"},
    {11622, "https://urkraft.se/fallfrukt/", "https://urkraft.se/feed/podcast/fallfrukt/"},
    {12275, "https://synergie.blogs.uni-hamburg.de/wp-admin/install.php",
     "https://synergie.blogs.uni-hamburg.de/feed/podcasts/"},
    {12492, "https://www.pacificdomains.net/moved.htmlfeed/",
     "http://www.radiocurious.org/feed/"},
    {12601,
     "http://www.pcsk9forum.org/newsletter/podcast-can-we-improve-fh-detection-by-learning-from-the-dutch/",
     "http://www.pcsk9forum.org/feed/podcast"},
    {12980, "https://www.hypnocast.com.br/cgi-sys/suspendedpage.cgi",
     "https://www.hypnocast.com.br/feed/podcast/"},
    {13023, "https://www.southcarolinapublicradio.org/podcast/health-focus",
     "https://www.southcarolinapublicradio.org/podcasts/9529/rss.xml"},
    {13149, "http://p3nlhclust404.shr.prod.phx3.secureserver.net/SharedContent/redirect_0.html",
     "https://www.ehlradio.com/ArchivedShows/ehlradio.xml"},
    {13185, "https://faithful-season.flywheelsites.com/podcasts/eco-radio-kc/feed/",
     "https://kkfi.org/podcasts/eco-radio-kc/feed/"},
    {13335, "https://cellculturedish.com/wp-content/uploads/sites/2/2020/05/podcast.png",
     "https://cellculturedish.com/feed/podcast/"},
    {13382, "https://www.facebook.com/blodadtandpodcast/?locale=sv_SE",
     "https://blodadtand.libsyn.com/rss"},
    {13682, "https://withwael.com/cgi-sys/suspendedpage.cgi",
     "https://withwael.com/feed/podcast/"},
    {13956, "http://feeds.feedburner.com/soundcloud/JiZN",
     "http://feeds.soundcloud.com/users/soundcloud:users:63507549/sounds.rss"},
    {14269, "http://p3nlhclust404.shr.prod.phx3.secureserver.net/SharedContent/redirect_0.html",
     "http://tttchristianyouth.org/podcast/podcast.xml"},
    {14545, "http://www.wvxu.drupal.publicbroadcasting.net/podcasts/74914/rss.xml",
     "http://wvxu.drupal.publicbroadcasting.net/podcasts/74914/rss.xml"},
    {14580, "http://homepage.mac.com/tom.bridges/podcast.xml",
     "http://www.apple.com/podcasts/vote_match/podcast.xml"},
    {14821,
     "https://www.sdmmag.com/gdpr-policy?url=https%3A%2F%2Fwww.sdmmag.com%2Fmedia%2Fpodcasts%2F2672-sdm-editors-podcast.rss",
     "https://www.sdmmag.com/media/podcasts/2672-sdm-editors-podcast.rss"},
    {15301, "https://podrevue.de/feed/mp4/", "https://hoerdateien.de/feed/podcast/podrevue"},
    {15350, "http://maintenance.pearsoncmg.com.s3-website-us-east-1.amazonaws.com/",
     "http://media.pearsoncmg.com/intl/ema/ema_uk_he_hogg_socpsych_5/podcasts/podcast.xml"},
    {15390,
     "https://podcastnorm.com/podcast-solutionsby-michael-geoghegan-and-dan-klass-this-months-book-reviewrecommendation/",
     "https://podcastnorm.com/feed/podcast/"},
    {15945, "https://www.bikeroute.com/cgi-sys/suspendedpage.cgi",
     "https://www.BikeRoute.com/PodcastXML/Virgi.xml"},
    {16229, "http://feeds.feedburner.com/MaximumCapacityShow",
     "http://feeds.soundcloud.com/users/soundcloud:users:24971267/sounds.rss"},
    {16420, "https://audioboom.com/users/2807972/posts.rss",
     "http://feeds.feedburner.com/audioboom/aDmW"},
    {17121, "https://www.healthcareinfosecurity.com/",
     "https://www.healthcareinfosecurity.com/itunes_rss_podcasts.php"},
    {17423, "http://www.frequencytheatre.co.uk/cgi-sys/suspendedpage.cgi",
     "http://www.frequencytheatre.co.uk/feed/podcast"},
    {17490, "http://aerstephen.rootswire.com/AerStephen.rootswire.com/folk_and_beyondNEW.xml",
     "http://aerstephen.rootswire.com/folk_and_beyondNEW.xml"},
    {17704, "https://anchor.fm/s/71d5234/podcast/rss",
     "http://feeds.soundcloud.com/users/soundcloud:users:158093478/sounds.rss"},
    {17857, "http://dowaradio.info/index20.rdf", "http://dowaradio.seesaa.net/index20.rdf"},
    {18089, "https://ctobob.com/2014/10/17/podcast-iaas/", "http://ctobob.com/feed/podcast/"},
    {18141, "https://www.cornerstonepodcast.org/cgi-sys/suspendedpage.cgi",
     "https://www.cornerstonepodcast.org/audio_podcast/bible_intensive/bible_intensive_podcast.xml"},
    {18360, "https://audioboom.com/users/4683417/posts.rss",
     "http://feeds.feedburner.com/CarlosHortasPodcast"},
    {18483, "https://audioboom.com/users/64589/posts.rss",
     "http://feeds.feedburner.com/brickbooks_podcast"},
    {18853, "https://audioboom.com/users/4308163/posts.rss",
     "http://feeds.feedburner.com/Apticotv"},
    {19056, "http://feeds.feedburner.com/abbpodcast",
     "http://feeds.soundcloud.com/users/soundcloud:users:13206887/sounds.rss"},
    {19265, "http://www.unwantedsound.com/cgi-sys/suspendedpage.cgi",
     "http://www.unwantedsound.com/feed/podcast"},
    {19761, "https://www.rts.ch/couleur3/programmes/point-barre/podcast/",
     "https://www.rts.ch/couleur3/programmes/point-barre/podcast/?flux=rss"},
    {19854, "https://eshop.macsales.com/podcasts/owcradio.xml",
     "https://www.macsales.com/podcasts/owcradio.xml"},
    {20122, "http://feeds.feedburner.com/feedssoundcloudcom/users/28376532-jojetltd/tracks",
     "http://feeds.soundcloud.com/users/soundcloud:users:28376532/sounds.rss"},
    {20580, "http://feeds.feedburner.com/Hyperbandrauschen", "https://hybr.de/feed/mp3/"},
    {20593,
     "https://www.deutschlandfunkkultur.de/podcast-breitband-medien-und-digitale-kultur-ganze-sendung-100.xml",
     "https://www.deutschlandfunkkultur.de/podcast-breitband-medien-und-digitale-kultur-ganze-sendung.1552.de.podcast.xml"},
    {20658, "https://www.podfeet.com/blog/category/ccatp/",
     "http://podfeet.com/ccatp/ccatp-rss.xml"},
    {21568, "https://www.nerdmate.defeed/aac", "https://nerdmate.de/feed/aac"},
    {21662, "http://kath-rottal.homeunix.org/AT/",
     "http://kath-rottal.homeunix.org/AT/MacTraining.xml"},
    {22124, "https://wartung.wdr.de",
     "https://www1.wdr.de/mediathek/audio/wdr2/wdr2-comedy/comedy-wdrzwei-podcast-100.podcast"},
    {22905, "https://www.hessenschau.de/hr-info_gespraech/podcast.xml",
     "https://podcast.hr.de/hr-info_gespraech/podcast.xml"},
    {23171, "https://blank.flywheelsites.com/feed/podcast/",
     "https://storyinabottle.charmingrobot.com/feed/podcast/"},
    {23197, "https://startupstory.biz/cgi-sys/suspendedpage.cgi",
     "https://startupstory.biz/feed/podcast"},
    {23204, "http://www.windcastlevc.com/cgi-sys/suspendedpage.cgi",
     "http://www.windcastlevc.com/feed/podcast/"},
    {23267, "http://www.nintendoteens.com/VMNoZ/SohWZ/RQRnZ/WjmmZ/topics/stpodcast/feed/",
     "http://feeds.soundcloud.com/users/soundcloud:users:237000142/sounds.rss"},
    {23313, "https://feedpress.me/si_public.xml", "https://feeds.simplecast.com/2atZBgbh"},
    {23730, "https://www.cram.org.br/cgi-sys/suspendedpage.cgi",
     "https://www.cram.org.br/papotech/ptr.xml"},
    {23731, "https://papotech.com.br/cgi-sys/suspendedpage.cgi",
     "https://papotech.com.br/podcast/papotech.xml"},
    {23940, "http://mastermibn.cluster020.hosting.ovh.net/mmradio.xml",
     "http://mastermibn.cluster020.hosting.ovh.net/masterminder/mmradiofr/itunespodcast/podcast/mmradio.xml"},
    {24046,
     "https://macmagazine.com.br/post/2008/01/04/podcast-102-do-gui-leite-conta-com-participacoes-e-previsoes-para-a-macworld/",
     "https://macmagazine.com.br/feed/podcast/"},
    {24257, "https://techcrunch.com/podcast/interviews",
     "http://www.spreaker.com/show/1553836/episodes/feed"},
    {24547, "http://www.wordswithgeeks.com/cgi-sys/suspendedpage.cgi",
     "http://www.wordswithgeeks.com/feed/podcast/"},
    {24665, "https://www.www.firpodcastnetwork.com/for-immediate-release/feed/",
     "https://www.firpodcastnetwork.com/for-immediate-release/feed/"},
    {24769, "https://feeds.podcastmirror.com/entertainment-2-0",
     "https://www.thedigitalmediazone.com/category/podcasts/entertainment-20/feed/"},
    {25150, "https://meinsportpodcast.de/404",
     "https://meinsportpodcast.de/fussball/weserfunk/feed/"},
    {25256, "https://www.macstories.net/podcasts/appstories/appstories-feed/",
     "https://appstories.net/episodes/feed/"},
    {25577, "http://feeds.feedburner.com/bestcast",
     "http://feeds.soundcloud.com/users/soundcloud:users:34187298/sounds.rss"},
    {26121, "https://wartung.wdr.de",
     "https://www1.wdr.de/mediathek/audio/wdr5/wdr5-morgenecho-glosse/satire-am-morgen-106.podcast"},
    {26189, "https://www.mehr-fuehren.de/podcast-die-drei-wichtigsten-fuehrungsprinzipien/",
     "http://www.mehr-fuehren.de/feed/podcast/"},
    {26272, "http://www.bitsundso.de/feed/plus/",
     "http://W37135:CLI8xaRn@www.bitsundso.de/feed/plus/"},
    {26748, "http://thetechwizard.blogspot.com/atom.xml",
     "http://feeds.feedburner.com/TheTechWizard"},
    {27048, "https://anchor.fm/s/8cf8d7c/podcast/rss",
     "http://feeds.soundcloud.com/users/soundcloud:users:118352154/sounds.rss"},
    {27364,
     "https://rmukeshgupta.com/podcast-episode-entrepreneur-in-focus-natasha-from-www-natsybydesign-com/",
     "http://rmukeshgupta.com/feed/podcast/"},
    {27396, "https://feeds.captivate.fm/produktivitet/", "http://produktiviteet.libsyn.com/rss"},
    {28023, "https://londonfintechpodcast.nxwave.uk/",
     "https://www.londonfintechpodcast.com/feed/podcast/"},
    {28039, "http://linkrot.net/podcast.rss", "http://linkrot.net/podcast.xml"},
    {28148, "https://lovingbdsm.net/2020/06/09/podcast-minisode-10-kneeling-alternatives/",
     "https://lovingbdsm.net/feed/podcast"},
    {28273, "http://wartung.wdr.de/",
     "https://www1.wdr.de/mediathek/audio/wdr5/wdr5-erlebte-geschichten/erlebte_geschichten108.podcast"},
    {28314, "http://kreativ.math.uni-bremen.de/podcast/podcast/podcast.xml",
     "http://kreativ.math.uni-bremen.de/podcast/podcast.xml"},
    {29559, "https://anchor.fm/s/22d729dc/podcast/rss",
     "https://businesswomenrock.libsyn.com/rss"},
    {29775, "https://anchor.fm/s/15e7dd48/podcast/rss", "http://socialladies.libsyn.com/rss"},
    {30940, "https://anchor.fm/s/e60057f8/podcast/rss",
     "https://feeds.acast.com/public/shows/6e0827b5-a9f6-4513-ac64-8dce16fddc26"},
    {31242, "http://oops.goalpoint.pt", "https://goalpoint.pt/feed/podcast"},
    {31401, "https://www.talkshoe.com/rss113085.xml",
     "http://fallscountanywhere.podomatic.com/rss2.xml"},
    {31989,
     "https://choice.npr.org/index.html?origin=https://www.npr.org/rss/podcast.php?id=344098539",
     "https://feeds.npr.org/344098539/podcast.xml"},
    {32479,
     "https://pistolsfiringblog.com/2015-sponsors-needed-pfb-podcast-and-newsletter/podcast/",
     "https://pistolsfiringblog.com/feed/podcast/"},
    {32549, "https://northernsun.org/sorry.ashx", "https://northernsun.org/podcast.aspx"},
    {32592, "http://psychicreform.com/cgi-sys/suspendedpage.cgi",
     "http://psychicreform.com/mosports/mosports.xml"},
    {32680, "https://pga13.eu/", "https://ausgespielt-podcast.de/feed/podcast/"},
    {32842, "https://wartung.wdr.de",
     "https://www1.wdr.de/mediathek/audio/wdr2/wdr2-kino/kino-podcast-100.podcast"},
    {32860, "https://hexenloft.spherearea.de/feed/mp3/",
     "https://lautfunk.uber.space/probepodcast/feed/mp3/"},
    {33267, "https://www.podbean.com/site/error?msg=user-site-page-not-found-router4",
     "https://www.bourbonboyspod.com/podcasts?format=rss"},
    {33620, "http://www.tracybreen.com/cgi-sys/suspendedpage.cgi",
     "http://www.tracybreen.com/feed/"},
    {33704,
     "http://www.surfguru.com/CMSMessages/Error.aspx?aspxerrorpath=/rss/surf-report-podcast.aspx",
     "http://www.surfguru.com/rss/surf-report-podcast.aspx"},
    {33873, "https://www.rideok.com/403.shtml", "http://www.rideok.com/feed/podcast/"},
    {34057, "https://www.lonestaroutdoorshow.com/cgi-sys/suspendedpage.cgi?feed=podcast",
     "https://www.lonestaroutdoorshow.com/?feed=podcast"},
    {34082, "https://feeds.simplecast.com/WvzZVSFW", "http://newagenomadpodcast.libsyn.com/rss"},
    {34099, "https://blog.murraysflyshop.com/podcast-part-i-102508/",
     "http://blog.murraysflyshop.com/feed/podcast/"},
    {34278, "https://www.geocaching.com/blog/2019/03/podcast-geocaching-le-hq-vu-de-linterieur/",
     "https://www.geocaching.com/blog/feed/podcast"},
    {34575, "https://ld21.de/feed/m4a/", "http://ld21.de/feed/m4a/"},
    {34585, "https://podcastdb29a3.podigee.io", "https://podcastdb29a3.podigee.io/feed/mp3"},
    {34586,
     "https://lautfunk.uber.space/monolog/feed/mp3/?doing_wp_cron=1779562633.1360950469970703125000",
     "https://lautfunk.uber.space/monolog/feed/mp3/"},
    {34587,
     "https://lautfunk.uber.space/feed/mp3/?doing_wp_cron=1779739047.0467569828033447265625",
     "https://lautfunk.uber.space/feed/mp3/"},
    {34596, "http://www.dansbikerides.com/cgi-sys/suspendedpage.cgi",
     "http://www.dansbikerides.com/rss.xml"},
    {35816, "https://www.coachjeff.com.au/cgi-sys/suspendedpage.cgi",
     "https://www.coachjeff.com.au/feed/triathlon-podcast/"},
    {36113, "http://feeds.feedburner.com/SugarFreeSportsPodcast",
     "http://feeds.soundcloud.com/users/soundcloud:users:15155357/sounds.rss"},
    {36926, "https://www.rnz.co.nz/podcasts/rss/extratime.rss",
     "https://www.rnz.co.nz/podcasts/extratime.rss"},
    {37444, "http://p3nlhclust404.shr.prod.phx3.secureserver.net/SharedContent/redirect_0.html",
     "http://www.thepainclinic.net/podclinic.rss"},
    {37722, "https://www.perfectlineups.com/cgi-sys/suspendedpage.cgi",
     "https://www.perfectlineups.com/feed/podcast/"},
    {37840, "http://p3nlhclust404.shr.prod.phx3.secureserver.net/SharedContent/redirect_0.html",
     "https://ozandking.com/?feed=podcast"},
    {37948, "http://cdn.stationcaster.com/stations/wgvx/rss/19103.rss",
     "https://audioboom.com/channels/3707831.rss"},
    {38063, "http://notthefootyshow.ashleymorrisonmedia.com/cgi-sys/suspendedpage.cgi",
     "http://notthefootyshow.ashleymorrisonmedia.com/feed/podcast/"},
    {38350, "https://www.mo-de.net/cgi-sys/suspendedpage.cgi",
     "https://www.mo-de.net/podcasts/acrobaticyoga_video_ipod/Motion_Design_Acrobatic_Yoga_Video_Ipod.xml"},
    {38534, "https://wartung.wdr.de",
     "https://www1.wdr.de/mediathek/audio/wdr5/wdr5-dok5-das-feature/dokfuenf140.podcast"},
    {39717, "http://goodmicworkcommentaries.com/cgi-sys/suspendedpage.cgi",
     "http://goodmicworkcommentaries.com/feed/podcast/"},
    {40272, "https://razzball.com/podcast-2016-finale/", "https://razzball.com/feed/podcast/"},
    {40480, "http://feeds.feedburner.com/DynastyDreamSequencePodcast",
     "http://feeds.soundcloud.com/users/soundcloud:users:229500821/sounds.rss"},
    {40578, "https://anchor.fm/s/d00389c/podcast/rss",
     "http://feeds.soundcloud.com/users/soundcloud:users:5349433/sounds.rss"},
    {41732, "https://will.illinois.edu/21stshow/podcast",
     "http://will.illinois.edu/bandwagon/rss"},
    {42053, "http://feeds.feedburner.com/afrshow",
     "http://feeds.soundcloud.com/users/soundcloud:users:270118504/sounds.rss"},
    {42558, "https://www.podomatic.com/404.html", "https://vasapodden.podomatic.com/rss2.xml"},
    {42584, "https://podcast.ntm.se/cgi-sys/suspendedpage.cgi",
     "https://podcast.ntm.se/feed/podcast/are-you-sirius"},
    {42672, "https://www.apfeltalk.de/install/index.php",
     "https://www.apfeltalk.de/magazin/feed/mp3/?paged=2"},
    {44453, "https://wartung.wdr.de",
     "https://www1.wdr.de/mediathek/audio/wdr-aktuell/wdr-aktuell-140.podcast"},
    {44508, "https://www.databreachtoday.com/",
     "https://www.databreachtoday.com/itunes_rss_podcasts.php"},
    {44772, "https://feeds.acast.com/public/shows/5f4f3b3a819cc91a1bf7c4bc",
     "http://feeds.soundcloud.com/users/soundcloud:users:288472852/sounds.rss"},
    {45590, "https://feed.podbean.com/itshanny/feed.xml",
     "https://feeds.soundcloud.com/users/soundcloud:users:234476591/sounds.rss"},
    {47392, "https://feeds.podcastmirror.com/eventual-millionaire",
     "http://eventualmillionaire.com/feed/podcast/?wpmfeedkey=28;d34e8d77f833838eae6cf7cf1bee78df"},
    {47472, "http://feeds.feedburner.com/entrypark",
     "http://feeds.soundcloud.com/users/soundcloud:users:174361838/sounds.rss"},
    {48248, "http://feeds.feedburner.com/DesignOfPodcast",
     "http://feeds.soundcloud.com/users/soundcloud:users:158251464/sounds.rss"},
    {48472, "http://feeds.feedburner.com/Daddydaughter101",
     "http://feeds.soundcloud.com/users/soundcloud:users:81831818/sounds.rss"},
    {48487, "http://www.jabernethy.com/cgi-sys/suspendedpage.cgi",
     "http://www.jabernethy.com/SeriesUnfortunateEvents.xml"},
    {48715, "https://caregivingmatters.ca/podcast-guest-experts/",
     "https://caregivingmatters.ca/feed/podcast/"},
    {49366, "https://cantwaitforchristmaspod.com/cgi-sys/suspendedpage.cgi",
     "https://cantwaitforchristmaspod.com/feed/podcast/"},
    {49449, "http://feeds.feedburner.com/butabupodcast",
     "http://feeds.soundcloud.com/users/soundcloud:users:270251270/sounds.rss"},
    {49687, "https://bobbyoinnercircle.com/podcast-396-john-krivit/",
     "https://bobbyoinnercircle.com/feed/podcast/"},
    {49777, "https://www.billselak.com/cgi-sys/suspendedpage.cgi?feed=podcast",
     "https://www.billselak.com/?feed=podcast"},
    {50185, "https://podcasts.flippedlearning.org/cgi-sys/suspendedpage.cgi",
     "https://podcasts.flippedlearning.org/askthefln/feed/"},
    {50199, "https://feedpress.me/cmc_public.xml", "https://feeds.simplecast.com/JBLCYmPD"},
    {50512, "http://aliceiseverywhere.com/cgi-sys/suspendedpage.cgi",
     "http://aliceiseverywhere.com/feed/podcast/"},
    {51071, "https://wartung.wdr.de",
     "https://www1.wdr.de/mediathek/audio/ball-you-need-is-love/ball-you-need-is-love-100.podcast"},
    {51297, "https://www.funkdisziplin.podigee.io/feed/mp3",
     "https://funkdisziplin.podigee.io/feed/mp3"},
    {51308, "https://wartung.wdr.de",
     "https://www1.wdr.de/mediathek/audio/wdr5/hintergrund-medien/hintergrund-medien-104.podcast"},
    {51389,
     "https://lautfunk.uber.space/probepodcast/feed/mp3/?doing_wp_cron=1779562650.0957748889923095703125",
     "https://lautfunk.uber.space/probepodcast/feed/mp3/"},
    {51403, "https://blogs.atzba.ch/wp-signup.php?new=www.traktorsound.de",
     "https://www.traktorsound.de/feed/mp3/"},
    {51407, "https://web.podcastlabel.de/", "https://qqq.quatschbroetchen.de/show/qee/feed/mp3/"},
    {51427, "https://www.nrwision.de/mediathek/sendungen/von-raedern/rss/100/",
     "https://www.nrwision.de/mediathek/sendungen/von-raedern/rss/100/feed.rss"},
    {51556, "https://www.deutschlandfunk.de/europa-heute-104.html",
     "https://www.deutschlandfunk.de/europa-heute-102.xml"},
    {52057, "https://https://podcasty.multilektor.pl//feed",
     "https://anchor.fm/s/46c418b4/podcast/rss"},
    {52275, "https://www.bbc.co.uk/programmes/b03m37fl/episodes/downloads.rss",
     "http://www.bbc.co.uk/programmes/b03m37fl/episodes/downloads.rss"},
    {52801, "https://linuxlads.com", "https://linuxlads.com/feed_mp3.rss"},
    {52893, "https://www.geschichtsschatten.ch/feed/mp3",
     "https://letscast.fm/podcasts/geschichtsschatten-c9520e56/feed"}
  ]

  def up do
    {ids, current_urls, previous_urls} =
      Enum.reduce(Enum.reverse(@restore), {[], [], []}, fn {id, current, previous}, {i, c, p} ->
        {[id | i], [current | c], [previous | p]}
      end)

    params = [ids, current_urls, previous_urls]

    restore = """
    SELECT f.id AS feed_id, f.podcast_id, r.current_url, r.previous_url
    FROM unnest($1::bigint[], $2::text[], $3::text[]) AS r(podcast_id, current_url, previous_url)
    JOIN feeds f ON f.podcast_id = r.podcast_id AND f.self_link_url = r.current_url
    """

    run("alternate_feeds rows added", params, """
    INSERT INTO alternate_feeds (feed_id, url, title, inserted_at, updated_at)
    SELECT r.feed_id, r.current_url, r.current_url,
           now() AT TIME ZONE 'UTC', now() AT TIME ZONE 'UTC'
    FROM (#{restore}) r
    WHERE NOT EXISTS (
      SELECT 1 FROM alternate_feeds a WHERE a.feed_id = r.feed_id AND a.url = r.current_url
    )
    """)

    run("podcasts made due now", params, """
    UPDATE podcasts p
    SET next_update = now() AT TIME ZONE 'UTC'
    FROM (#{restore}) r
    WHERE p.id = r.podcast_id AND NOT p.retired AND NOT p.update_paused
    """)

    run("feed urls restored", params, """
    UPDATE feeds f
    SET self_link_url = r.previous_url, updated_at = now() AT TIME ZONE 'UTC'
    FROM (#{restore}) r
    WHERE f.id = r.feed_id
    """)
  end

  defp run(label, params, sql) do
    %{num_rows: num_rows} = repo().query!(sql, params)
    IO.puts("#{label}: #{num_rows}")
  end

  # Not reversible: the broken URLs stay in alternate_feeds, but the feeds
  # may have moved on by their own redirects since.
  def down, do: :ok
end
