module.exports = {
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',      

    // base colors
      'blue-jeans-light': '#5d9cec', 
      'blue-jeans': '#4a89dc',
      'aqua-light': '#4fc1e9', 
      'aqua': '#3bafda',
      'mint-light': '#48cfad', 
      'mint': '#37bc9b',
      'grass-light': '#a0d468', 
      'grass': '#8cc152',
      'sunflower-light': '#ffce54', 
      'sunflower': '#f6bb42',
      'bittersweet-light': '#fc6e51', 
      'bittersweet': '#e9573f',
      'grapefruit-light': '#ed5565', 
      'grapefruit': '#da4453',
      'lavender-light': '#ac92ec', 
      'lavender': '#967adc',
      'pink rose-light': '#ec87c0', 
      'pink rose': '#d770ad',
      'light gray-light': '#f5f7fa', 
      'light gray': '#e6e9ed',
      'medium gray-light': '#ccd1d9', 
      'medium gray': '#aab2bd',
      'dark gray-light': '#656d78', 
      'dark gray': '#434a54"',

    // shades of gray
       'white': '#FFFFFF',
       'very-light-gray': '#F5F7FA',
       'light-gray': '#E6E9ED',
       'light-medium-gray': '#CCD1D9',
       'medium-gray': '#AAB2BD',
       'medium-dark-gray': '#656D78',
       'dark-gray': '#434A54',
       'black': '#000000',

    // functional colors
       'nav-background': '#434a54', // dark gray
       'success-light': '#b9df90',
       'success': '#8cc152', // grass
       'success-dark': '#3c763d',
       'warning-light': '#ffdd87',
       'warning': '#f6bb42', // sunflower
       'warning-dark': '#8a6d3b',
       'danger-light': '#f2838f',
       'danger': '#da4453', // grapefruit
       'danger-dark': '#a94442',
       'info-light': '#7cd1ef',
       'info': '#3bafda', // aqua
       'info-dark': '#31708f',

    // full color palette
      'foreign-crimson': '#c91f37',
      'red-orange': '#dc3023',
      'cochineal-red': '#9d2933',
      'monza': '#cf000f',
      'brewed-mustard-brown': '#e68364',
      'pomegranate': '#f22613',
      'scarlet': '#cf3a24',
      'pure-crimson': '#c3272b',
      'true-red': '#8f1d21',
      'chestnut-rose': '#d24d57',
      'one-kin-dye': '#f08f907',
      'peach-colored': '#f47983',
      'red-plum-colored': '#db5a6b',
      'medium-crimson': '#c93756',
      'cherry-blossom-color': '#fcc9b9',
      'washed-out-crimson': '#ffb3a7',
      'radical-red': '#f62459',
      'ibis-wing-color': '#f58f84',
      'wisteria-purple': '#875f9a',
      'bellflower-color': '#5d3f6a',
      'wisteria-color': '#89729e',
      'iris-color': '#763568',
      'tatarian-aster-color': '#8d608c',
      'thin-color': '#a87ca0',
      'violet-color': '#5b3256',
      'medium-purple': '#bf55ec',
      'studio': '#8e44ad',
      'wisteria': '#9b59b6',
      'light-wisteria': '#be90d4',
      'sky-color': '#4d8fac',
      'ultramarine-color': '#5d8cae',
      'picton-blue': '#22a7f0',
      'dodger-blue': '#19b5fe',
      'picton-blue': '#59abe3',
      'light-blue-color': '#48929b',
      'thousand-herb': '#317589',
      'jordy-blue': '#89c4f4',
      'steel-blue': '#4b77be',
      'lapis-lazuli-color': '#1f4788',
      'navy-blue-color': '#003171',
      'hanada': '#044f67',
      'indigo-color': '#264348',
      'siskin-sprout-yellow': '#7a942e',
      'young-green-onion': '#8db255',
      'fresh-onion': '#5b8930',
      'young-bamboo-color': '#6b9362',
      'patina': '#407a52',
      'green-bamboo': '#006442',
      'gossip': '#87d37c',
      'eucalyptus': '#26a65b',
      'jungle-green': '#26c281',
      'observatory': '#049372',
      'jungle-green': '#2abb9b',
      'mountain-meadow': '#16a085',
      'turquoise': '#36d7b7',
      'free-speech-aquamarine': '#03a678',
      'ocean-green': '#4daf7c',
      'patrinia-flowers': '#d9b611',
      'amur-cork-tree': '#f3c13a',
      'ripe-lemon': '#f7ca18',
      'japanese-triandra-grass': '#e2b13c',
      'rapeseed-oil-colored': '#a17917',
      'cream-can': '#f5d76e',
      'saffron': '#f4d03f',
      'bright-golden-yellow': '#ffa400',
      'sumac-dyed': '#e08a1e',
      'gamboge': '#ffb61e',
      'corn-colored': '#faa945',
      'egg-colored': '#ffa631',
      'floral-leaf-colored': '#ffb94e',
      'golden-fallen-leaves': '#e29c45',
      'ecstasy': '#f9690e',
      'amber': '#ca6924',
      'lightning-yellow': '#f5ab35',
      'silver': '#bfbfbf',
      'cararra': '#f2f1ef',
      'silver-sand': '#bdc3c7',
      'porcelain': '#ecf0f1',
      'pumice': '#d2d7d3',
      'harbor-rat': '#757d75',
      'gallery': '#eeeeee',
      'edward': '#abb7b7',
      'lynch': '#6c7a89',
      'cascade': '#95a5a6',
    }
  }
}

